
  const ENTITY_CATALOG = Object.freeze({
    providers: Object.freeze([
      "01.AI",
      "AI21 Labs",
      "Alibaba",
      "Amazon",
      "Amazon Bedrock",
      "Anthropic",
      "Azure",
      "Baseten",
      "ByteDance",
      "Cerebras",
      "Chutes",
      "Cohere",
      "DeepInfra",
      "DeepSeek",
      "Featherless",
      "Fish Audio",
      "Fireworks AI",
      "Google",
      "Google AI Studio",
      "Google Vertex",
      "Groq",
      "Hugging Face",
      "Hyperbolic",
      "Inception",
      "InclusionAI",
      "Lambda",
      "Meta",
      "Microsoft",
      "MiniMax",
      "Mistral",
      "Moonshot AI",
      "Nebius",
      "Nous Research",
      "NovitaAI",
      "NVIDIA",
      "OpenAI",
      "OpenRouter",
      "Perplexity",
      "Qwen",
      "Replicate",
      "SambaNova",
      "StepFun",
      "Tencent",
      "Thinking Machines",
      "Together AI",
      "xAI",
      "Z.AI",
      "Black Forest Labs",
    ]),
    modelFamilies: Object.freeze([
      "Claude",
      "Command R",
      "DBRX",
      "DeepSeek",
      "FLUX",
      "Gemini",
      "Gemma",
      "GLM",
      "GPT",
      "Grok",
      "Hermes",
      "Inkling",
      "Jamba",
      "Kimi",
      "Llama",
      "Mistral",
      "Mixtral",
      "Nemotron",
      "Nova",
      "Phi",
      "Qwen",
      "Seedance",
      "Sonar",
      "Yi",
      "o1",
      "o3",
      "o4",
    ]),
    stableLabels: Object.freeze([
    "OpenRouter",
    "OpenAI",
    "Anthropic",
    "Artificial Analysis",
    "Design Arena",
    "GPQA Diamond",
    "τ²-Bench Airline",
    "TAU-Bench",
    "HLE",
    "AA-LCR",
    "GDPval-AA",
    "CritPt",
    "SciCode",
    "IFBench",
    "LiveCodeBench",
    "Terminal-Bench Hard",
    "AA-Omniscience",
    "τ²-Bench Telecom",
    "TIGER Lab",
    "NYU & Collaborators",
    "Centre for AI Safety",
    "Google Research",
    "CMU & MBZUAI",
    "Stanford & Collaborators",
    "MAA",
    "GitHub",
    "Discord",
    "LinkedIn",
    "YouTube",
    "Ori",
    "Replit",
    "Hermes Agent",
    "Kilo Code",
    "SDK",
    "API",
    "ELO",
    "Elo",
    "BYOK",
    "SSO",
    "SAML",
    "SLA",
    "ZDR",
    "GDPR",
    "SOC-2",
    "OpenAPI",
    "Swagger UI",
    "Postman",
    "LangChain",
    "LiveKit",
    "PydanticAI",
    "Vercel AI SDK",
    "Open WebUI",
    "Cloudflare AI Gateway",
    "NIST",
    "CAISI",
    "MIT",
    "Boston University",
    "Brookings Institution",
    "Reuters",
    "Cisco",
    "npm",
    "pnpm",
    "Yarn",
    "Bun",
    "Deno",
    "pip",
    "Python",
    "TypeScript",
    "JavaScript",
    "Shell",
    "cURL",
    "Ruby",
    "PHP",
    "Go",
    "Java",
    "Rust",
    "C#",
    "Node.js",
    "Kotlin",
    "Swift",
    "callModel",
    ]),
  });

  const PROTECTED_LABELS = new Set([
    ...ENTITY_CATALOG.providers,
    ...ENTITY_CATALOG.modelFamilies,
    ...ENTITY_CATALOG.stableLabels,
  ]);

  const PROTECTED_ENTITY_PATTERN_SOURCE = [...new Set([
    ...ENTITY_CATALOG.providers,
    ...ENTITY_CATALOG.modelFamilies.filter((name) => name.length >= 3),
  ])]
    .sort((left, right) => right.length - left.length)
    .map((name) => name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
    .join("|");
